title: Heejin Eun
description: Welcome to my website.
baseurl: ""
url: "https://heeheejinag.github.io/"

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: Heejin Eun
  email: aghj@korea.ac.kr
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: 82 010 

# social media links
social:
  facebook: username
  x: username
  mastodon:
    user: username
    domain: mastodon.social
  bluesky:
    user: username
    domain: bsky.social
  instagram: username
  linkedin: username
  xing: username
  stackoverflow: 0000000/username
  medium: username
  github: username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
